apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demoapp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demoapp
spec:
  source:
    git:
      url: https://github.com/mu853/demoapp
      ref:
        branch: master